# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# History Fix - https://stackoverflow.com/questions/10488498/bash-history-does-not-update-in-git-for-windows-git-bash
PROMPT_COMMAND='history -a'
